### PR TITLE
Added UTair-MVP-Sample

### PR DESCRIPTION
**Pull request by ImangazalievM**
Added https://github.com/ImangazalievM/UTair-MVP-Sample

### CODE REVIEW

**Review by androiddevnotes — CHANGES_REQUESTED** [review]
Thank you for your PR. The repo looks interesting.

You forgot to change the URL to your repo. Please update the commit.

**Comment by ImangazalievM** [comment]
@androiddevnotes fixed

**Review by androiddevnotes — APPROVED** [review]
Thank you! 🐣

**Review by androiddevnotes — APPROVED** [review]
If you want to be a contributor or author to one of our repos or simply want to be part of Android OSS, please Join the discord community:

Invite Link: https://discord.gg/vBnEhuC

Thank you!

**Pull request merged**
