### PR TITLE
Add TimelineView

### PR DESCRIPTION
**Pull request by anacoimbrag**
- Add study section with Android Developer Roadmap
- Add TimelineView as a lib.

### CODE REVIEW

**Review by androiddevnotes — CHANGES_REQUESTED** [review]
Thank you for the Pull Request!

This PR is better suited for https://github.com/androiddevnotes/awesome-android-learning-resources#other

Here: Android Learning Resource repo Under Docs/Other > Other

Please create the PR on the above repo linked.

Please join the Discord server where we discuss open-source, android dev, and content creation. Invite link - https://discord.gg/vBnEhuC

**Review by androiddevnotes — CHANGES_REQUESTED** [review]
Remove the Study section part and keep the timeline-view entry and do another commit. Thank you : )

**Comment by anacoimbrag** [comment]
@androiddevnotes sorry for this misunderstanding! Already  changed the code removing the study section.
I've entered the discord server, that's awesome! Thanks for sharing 😊

**Review by androiddevnotes — APPROVED** [review]
Thank you for the Pull Request!

Please join the Discord server where we discuss open-source, android dev, and content creation. Invite link - https://discord.gg/vBnEhuC

**Pull request merged**
